name: Pong

on: [repository_dispatch]
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/phpcollab/phpcollab/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H "Content-Type:application/json" \
          -H "Authorization: token ${{ secrets.JS_ACCESS_TOKEN }}" \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
