name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
          docker buildx build --pull --push \
          --build-arg PHPVERSION=7.4 \
          --build-arg VARIANT=apache \
          --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
          --tag phpcollab/phpcollab:latest \
          --tag phpcollab/phpcollab:2 \
          --tag phpcollab/phpcollab:2.8 \
          --tag phpcollab/phpcollab:2.8.1 \
          --tag phpcollab/phpcollab:2.8.1-apache \
          .
